/*
 *  SFeditor - Star Fighter 3000 map/mission editor
 *  Editor change declarations
 *  Copyright (C) 2022 Christopher Bazley
 */

DECLARE_CHANGE(TEX_FIRST)
DECLARE_CHANGE(TEX_ALL_RELOADED)
DECLARE_CHANGE(TEX_GROUPS_RELOADED)
DECLARE_CHANGE(TEX_SNAKES_RELOADED)
DECLARE_CHANGE(TEX_TRANSFERS_RELOADED)
DECLARE_CHANGE(TEX_TRANSFER_ADDED)
DECLARE_CHANGE(TEX_TRANSFER_ALL_DELETED)
DECLARE_CHANGE(TEX_TRANSFER_DELETED)
DECLARE_CHANGE(TEX_TRANSFER_REPLACED)
DECLARE_CHANGE(TEX_TRANSFER_RENAMED)
DECLARE_CHANGE(TEX_LIMIT)
DECLARE_CHANGE(GFX_FIRST)
DECLARE_CHANGE(GFX_ALL_RELOADED)
DECLARE_CHANGE(GFX_SNAKES_RELOADED)
DECLARE_CHANGE(GFX_TRANSFERS_RELOADED)
DECLARE_CHANGE(GFX_TRANSFER_ADDED)
DECLARE_CHANGE(GFX_TRANSFER_ALL_DELETED)
DECLARE_CHANGE(GFX_TRANSFER_DELETED)
DECLARE_CHANGE(GFX_TRANSFER_REPLACED)
DECLARE_CHANGE(GFX_TRANSFER_RENAMED)
DECLARE_CHANGE(GFX_LIMIT)
DECLARE_CHANGE(CLOUD_COLOURS)
DECLARE_CHANGE(HILL_COLOURS)
DECLARE_CHANGE(POLYGON_COLOURS)
DECLARE_CHANGE(OBJ_PRECHANGE) // pre- to allow undraw of selected/occluded
DECLARE_CHANGE(OBJ_PREMOVE)
DECLARE_CHANGE(MAP_PRECHANGE) // pre- to allow undraw of selected/occluded
DECLARE_CHANGE(MAP_PREMOVE)
DECLARE_CHANGE(INFO_ADDED)
DECLARE_CHANGE(INFO_PREDELETE) // pre- to allow undraw of selected/occluded
DECLARE_CHANGE(INFO_MOVED)
DECLARE_CHANGE(MISSION_REPLACED)
DECLARE_CHANGE(MAP_ALL_REPLACED)
DECLARE_CHANGE(OBJ_ALL_REPLACED)
DECLARE_CHANGE(BRIEFING)

